
version: "3.3"
services:
  image:
    image: 192.168.0.119:50000/version
    build: .
    network_mode: &nmode "host"
  version-test:
    image: 192.168.0.119:50000/version
    command: version.py
    volumes: &volumes
      - ./test/:/home/root/workdir/
    network_mode: *nmode
  package-test:
    image: 192.168.0.119:50000/version
    command: version.py -p test -a amd64
    volumes: *volumes
    network_mode: *nmode
  next-version-test:
    image: 192.168.0.119:50000/version
    command: version.py --next
    volumes: *volumes
    network_mode: *nmode
  next-fix-version-test:
    image: 192.168.0.119:50000/version
    command: version.py --next-fix -a lol
    volumes: *volumes
    network_mode: *nmode
  next-hotfix-version-test:
    image: 192.168.0.119:50000/version
    command: version.py --next-hotfix
    volumes: *volumes
    network_mode: *nmode
  change-version-test:
    image: 192.168.0.119:50000/version
    command: version.py --next -w
    volumes: *volumes
    network_mode: *nmode
  commit-version-test:
    image: 192.168.0.119:50000/version
    command: version.py -e test/.env --next -w -c "test tag" -u "Manuel Pascual López" "manuel.pascual@sedecal.com" --private-key "$PRIVATE_KEY"
    volumes:
      - ./:/home/root/workdir/
    network_mode: *nmode
    environment:
      - PRIVATE_KEY # export PRIVATE_KEY="$(cat ~/.ssh/id_rsa)"
  check:
    image: hadolint/hadolint
    command: hadolint /var/repo/Dockerfile
    volumes:
      - ./:/var/repo
    network_mode: *nmode
  brancheck-test:
    image: 192.168.0.119:50000/version
    command: brancheck.py refs/heads/feature/lol refs/heads/development
    volumes: *volumes
    network_mode: *nmode
