
version: "3.3"
services:
  image:
    image: 192.168.0.119:50000/version
    build: .
  version-test:
    image: 192.168.0.119:50000/version
    command: version.py
    volumes:
      - ./test/:/home/root/workdir/
  package-test:
    image: 192.168.0.119:50000/version
    command: version.py -p test -a amd64
    volumes:
      - ./test/:/home/root/workdir/
  next-version-test:
    image: 192.168.0.119:50000/version
    command: version.py --next
    volumes:
      - ./test/:/home/root/workdir/
  next-fix-version-test:
    image: 192.168.0.119:50000/version
    command: version.py --next-fix -a lol
    volumes:
      - ./test/:/home/root/workdir/
  next-hotfix-version-test:
    image: 192.168.0.119:50000/version
    command: version.py --next-hotfix
    volumes:
      - ./test/:/home/root/workdir/
  change-version-test:
    image: 192.168.0.119:50000/version
    command: version.py --next -w
    volumes:
      - ./test/:/home/root/workdir/
  check:
    image: hadolint/hadolint
    command: hadolint /var/repo/Dockerfile
    volumes:
      - ./:/var/repo
  brancheck-test:
    image: 192.168.0.119:50000/version
    command: brancheck.py $SOURCE $TARGET
    volumes:
      - ./test/:/home/root/workdir/
    environment:
      - SOURCE
      - TARGET
