
version: "3.3"
services:
  image:
    image: &image 192.168.0.119:50000/version:azure
    build: .
    network_mode: &nmode "host"
  shell:
    image: *image
    command: /bin/bash
    volumes:
      - ./:/home/root/workdir/
    network_mode: *nmode
    working_dir: /home/root/workdir/
    user: "${EXTERNAL_UID:-1000}:${EXTERNAL_GID:-1000}"
  lint-docker:
    image: hadolint/hadolint
    command: hadolint /var/repo/Dockerfile
    volumes:
      - ./:/var/repo
    network_mode: *nmode
  test: # run unit tests
    image: python:3.8.10
    command: | 
      /bin/bash -c "
        set -e
        echo 'Brancheck tests:'
        python3 -m test.brancheck_test
        echo 'Version tests:'
        python3 -m test.version_test
        echo 'Project name tests:'
        python3 -m test.project_test
        echo 'All test went ok'
      "
    volumes:
      - ./:/home/root/workdir/
    network_mode: *nmode
    working_dir: /home/root/workdir/
    user: "${EXTERNAL_UID:-1000}:${EXTERNAL_GID:-1000}"
